"""The Help panel: a taught tour of the workstation, generated from the real thing.

The architectural rule of this module is that **help content is data**. Every tab is a
list of :class:`Section`/:class:`Entry`/:class:`Step` records rendered by one small set of
generic drawing functions. Nothing here is a wall of hand-inlined ``imgui.text`` calls,
because that shape of code is what makes a Help panel rot: it is too expensive to edit, so
nobody edits it, and within a release it is lying to the user.

Two tabs are not authored at all, they are *derived*:

* **Keyboard** is generated from :class:`~glplot.gui.actions.ActionRegistry` -- titles,
  categories and chords come straight out of the registry the keymap dispatches from, so a
  rebound or renamed action updates Help for free and a hand-written list cannot drift out
  of sync. Registry conflicts (:meth:`~glplot.gui.actions.ActionRegistry.conflicts`) are
  surfaced here too: a chord bound twice is a silently dead binding otherwise.
* **Expressions** is generated by walking :data:`glplot.gui.expressions.SAFE_NAMES`, the
  same dict the evaluator's allowlist is built from. :data:`_EXPR_DOCS` supplies prose for
  each name; a name present in ``SAFE_NAMES`` but missing from the doc table still renders
  (signature introspected, description taken from the docstring), so adding a function to
  the evaluator can never silently drop it out of the reference.

The engine's own hotkeys are the one hand-transcribed list, because they have no registry:
their source of truth is ``glplot/engine.py::_on_key`` and they are copied from it. See
:data:`_ENGINE_HOTKEYS`.
"""

from __future__ import annotations

import inspect
import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from .. import expressions, fuzzy, keys
from .base import Panel

try:
    from imgui_bundle import imgui

    IMGUI_AVAILABLE = True
except (ImportError, Exception):  # pragma: no cover - GL-less import guard
    IMGUI_AVAILABLE = False
    imgui = None

logger = logging.getLogger(__name__)

__all__ = ["Entry", "HelpPanel", "Section", "Step"]

#: Width of the right-hand shortcut column, in points.
_KEY_COLUMN_W = 132.0
#: Width of the expression-signature column, in points.
_SIGNATURE_COLUMN_W = 210.0


# ======================================================================================
# Content model
# ======================================================================================


@dataclass(frozen=True)
class Entry:
    """One row of a section: a label, a value column, and an optional dimmed note.

    The meaning of ``value`` is per-tab: a formatted chord in Keyboard, a signature in
    Expressions, a key name in Panels. ``insert`` is the Expressions tab's payload -- the
    text its "Insert" button drops into the Functions panel; an empty string means the row
    has no button.
    """

    label: str
    value: str = ""
    note: str = ""
    insert: str = ""

    def labels(self) -> Tuple[str, ...]:
        """The short fields, matched fuzzily."""
        return (self.label, self.value)

    def prose(self) -> Tuple[str, ...]:
        """The long fields, matched by substring (see :meth:`HelpPanel._matches`)."""
        return (self.note,)


@dataclass(frozen=True)
class Section:
    """A titled group of entries under a collapsing header."""

    title: str
    intro: str = ""
    entries: Tuple[Entry, ...] = ()
    #: Header for the value column. Empty hides the table header row entirely.
    value_header: str = ""
    #: Fixed width of the value column, in points.
    value_width: float = _KEY_COLUMN_W
    #: True for the Expressions tab, whose rows carry an Insert button.
    insertable: bool = False


@dataclass(frozen=True)
class Step:
    """One numbered step of the Getting Started tour, with a button that really runs it.

    ``action_id`` is tried against the workspace's registry first, so the button does
    exactly what the equivalent shortcut does. ``panel`` is the fallback for a workspace
    whose registry does not (yet) carry that id -- opening the panel is always meaningful,
    and a Help button that silently does nothing is worse than no button.
    """

    title: str
    body: str
    button: str
    action_id: Optional[str] = None
    panel: Optional[str] = None


# ======================================================================================
# Authored content
# ======================================================================================

_STEPS: Tuple[Step, ...] = (
    Step(
        title="Paste your data",
        body=(
            "Open the Data panel and press Paste with a table on the clipboard — a block "
            "of cells copied straight out of Excel, Numbers or a text file works as-is "
            "(it is tab-separated text). A first row of names becomes the column headers. "
            "No clipboard? Press New for an empty sheet and type into it."
        ),
        button="Open Data",
        action_id="panel.data",
        panel="data",
    ),
    Step(
        title="Plot it",
        body=(
            "Still in Data: open 'Plot & link', choose which column is x and which is y, "
            "and press Plot. The new layer stays bound to the table — edit a cell and the "
            "curve moves with it. That link is the point of the panel; a plot made this "
            "way is never a dead copy of your numbers."
        ),
        button="Plot the dataset",
        action_id="data.plot",
        panel="data",
    ),
    Step(
        title="Write a function",
        body=(
            "The Functions panel turns an expression in x into a curve: try "
            "a * sin(b * x) * exp(-x / 5). Any name the evaluator does not know — a, b, k "
            "— becomes a parameter slider automatically; drag one and the preview follows "
            "immediately. Set the domain and sample count under Domain, then press Plot."
        ),
        button="Open Functions",
        action_id="panel.functions",
        panel="functions",
    ),
    Step(
        title="Transform it",
        body=(
            "Math Lab operates on the selected layer: integral, derivative, smoothing, "
            "FFT, polynomial fit, statistics, noise. Every operation previews its result "
            "over the original first — nothing touches the scene until you press Apply, "
            "and Apply is undoable."
        ),
        button="Open Math Lab",
        action_id="panel.mathlab",
        panel="mathlab",
    ),
    Step(
        title="Style it",
        body=(
            "Scene lists every layer: select, rename, hide, solo, drag to reorder. Style "
            "edits the selected one — color, line width, point size, alpha, draw order — "
            "and the plot updates live as you drag. From here on, the fastest way to find "
            "anything is the command palette."
        ),
        button="Open Style",
        action_id="panel.style",
        panel="style",
    ),
)


#: The engine's bare-key hotkeys. **Source of truth: ``glplot/engine.py::_on_key``** —
#: they are not in the action registry, so unlike the rest of the Keyboard tab this list is
#: transcribed by hand and must be re-read against ``_on_key`` when that function changes.
_ENGINE_HOTKEYS: Tuple[Entry, ...] = (
    Entry("Reset the view", "R  ·  Home", "Frames the scene again. Repeats while held."),
    Entry("Toggle density rendering", "D", "Swaps exact lines for the density accumulator."),
    Entry("Toggle the line colormap", "C"),
    Entry("Cycle the blend mode", "B"),
    Entry("Toggle the HUD", "H", "Hides this whole interface, including these panels."),
    Entry(
        "Save a PNG",
        "S",
        "Writes plot_<timestamp>.png into the working directory at the export scale.",
    ),
    Entry("Send the scene to matplotlib", "M", "Opens the current view as a matplotlib figure."),
    Entry("Toggle auto-alpha", "\\"),
    Entry("Density gain down / up", "[  ·  ]", "Repeats while held."),
    Entry("Previous / next density colormap", "←  ·  →", "11 schemes, Classic through Cool."),
    Entry(
        "Density gain ×1.2 / ÷1.2",
        "↑  ·  ↓",
        "Only while density rendering is on; otherwise these scale the global alpha.",
    ),
    Entry("Zoom in / out", "=  ·  -", "About the centre of the viewport. Keypad +/- also work."),
    Entry(
        "Toggle the profiler overlay",
        "F3",
        "Turning it on forces the HUD back on with it.",
    ),
    Entry("Close the window", "Esc"),
)

_ENGINE_INTRO = (
    "These are the plot engine's own hotkeys, handled in engine._on_key rather than by the "
    "action registry. They are bare keys with no modifier, so they fire only when no text "
    "field has keyboard focus — while you are typing in a cell or an expression, every one "
    "of them is suppressed."
)


_PANEL_SECTIONS: Tuple[Section, ...] = (
    Section(
        title="Data — the spreadsheet",
        intro=(
            "A real grid: paste a table in, edit cells, sort, add rows and columns, import "
            "and export CSV. A dataset plotted from here stays bound to its layer, so an "
            "edit rewrites the curve in place. The keys below apply while the grid has "
            "focus."
        ),
        value_header="Key",
        entries=(
            Entry("Move the cursor", "Arrows", "Hold Shift to extend the selection."),
            Entry("Move by a page", "PageUp / PageDown", "20 rows at a time."),
            Entry("Jump to the first / last row", "Home / End"),
            Entry("Edit the cell", "Enter"),
            Entry("Commit and step right", "Tab", "Shift+Tab steps left."),
            Entry("Cancel the edit", "Esc", "Clicking away commits instead."),
            Entry("Copy / paste / cut", "Ctrl+C / V / X", "Tab-separated — Excel round-trips."),
            Entry("Select the whole table", "Ctrl+A"),
            Entry("Clear the selected values", "Delete / Backspace"),
        ),
    ),
    Section(
        title="Functions — expression to curve",
        intro=(
            "Type an expression in x. Names the evaluator does not know become parameter "
            "sliders, and the preview re-evaluates as you drag them. Plot adds a new layer; "
            "Replace overwrites the curve you generated last, which is how you iterate "
            "without piling up layers. See the Expressions tab for every name you can use."
        ),
    ),
    Section(
        title="View 3D — the camera and the box",
        intro=(
            "Everything about how a 3D figure is seen: the 2D/3D mode switch, the camera "
            "(elevation, azimuth, roll, distance, field of view), perspective vs "
            "orthographic projection, the axis decoration (box, floor, grid walls, tick "
            "marks and numbers, axis titles), the axis scaling, and ambient occlusion. "
            "There is one camera per panel, so a split figure can hold a 2D plot beside a "
            "3D one."
        ),
        value_header="Gesture",
        entries=(
            Entry("Orbit around the target", "Drag"),
            Entry("Pan (slide the target)", "Ctrl+Drag", "Right-drag and middle-drag do the same."),
            Entry("Roll about the line of sight", "Alt+Drag"),
            Entry("Dolly in and out", "Scroll"),
            Entry("Reset the view", "Home button", "Orientation, dolly and pan at once."),
            Entry("Fit the data", "Target button", "Keeps the orientation."),
        ),
    ),
    Section(
        title="Objects 3D — the shape catalogue",
        intro=(
            "Twenty-seven parametric objects in five groups: space curves (helix, torus "
            "knot, Lissajous), surfaces (sphere, torus, Möbius strip, Klein bottle, "
            "saddle, ripple, seashell), point clouds, lattices and vector fields. Each has "
            "sliders and a sample count; Plot adds it as a layer and registers its table "
            "in the Data panel, so a generated object is an ordinary dataset you can edit, "
            "filter and re-plot like any other."
        ),
    ),
    Section(
        title="Plotting in 3D",
        intro=(
            "Three columns reach nine plot types. In the Data panel, switch 'Plot as' to "
            "3D and pick the x, y and z columns: scatter, line (path), stems, ribbon, "
            "bars, surface, wireframe, volumetric cloud and vector field. Surface and "
            "wireframe need the x/y columns to form a rectangular grid — build one with "
            "z = f(x, y) in the Functions panel, whose 'Draw as' picker offers a heat map, "
            "a surface or a wireframe from the same expression.\n\n"
            "In the Dynamics panel, choosing a Z axis plots the trajectory as a space "
            "curve instead of a 2D projection, which is the only way an attractor reads "
            "as its actual shape."
        ),
    ),
    Section(
        title="Timeline — animation",
        intro=(
            "An animation here is a set of keyframes on a timeline, not a script you run. "
            "Key a value at one time and another value at a later time, and everything in "
            "between is computed — which is why it can be scrubbed, looped and exported "
            "deterministically.\n\n"
            "**The short way in is Capture.** Aim the figure however you want it, press "
            "**K**, move the playhead, aim it somewhere else, press **K** again — that is a "
            "camera move, and you never had to know that the azimuth is spelled `azim`. "
            "Capture creates whatever tracks it needs, so it works on an empty timeline; "
            "the picker beside the button says what it records (the camera, every layer's "
            "style, both, or only what is already animated).\n\n"
            "In a 3D figure the **number keys 1-9 snap to the standard angles** — front, "
            "back, left, right, top, bottom, then the three isometrics — and 0 resets the "
            "view. Together with K that makes a camera move a handful of keystrokes.\n\n"
            "**Quick animations** is the other short way in: pick a preset and press Build, "
            "and a whole animation appears — a turntable, a tour of four angles, a "
            "staggered reveal of the layers, a draw-on that traces each layer along its own "
            "path. They are built out of the same verbs a script would use "
            "(`glplot.anim.primitives`), so what you get is ordinary keyframes on ordinary "
            "tracks: drag them, retime them, change their easing. Tick 'Build from the "
            "playhead' to chain one after another.\n\n"
            "Anything with a number can be keyed: a layer's opacity, colour, size or "
            "position; the 2D camera's pan and zoom; and in 3D the elevation, azimuth, "
            "roll, distance, field of view and axis scaling. A track is one property of one "
            "target."
        ),
        value_header="Control",
        entries=(
            Entry(
                "Capture the figure now",
                "Capture keyframe (K)",
                "Records the current state at the playhead and creates the tracks it needs. "
                "The one authoring gesture that works on an empty timeline.",
            ),
            Entry(
                "Snap to a standard angle",
                "1-9 (0 resets)",
                "Front, back, left, right, top, bottom, then three isometrics. 3D only.",
            ),
            Entry(
                "Build a whole animation",
                "Quick animations",
                "Turntable, grand tour of the standard angles, rock, push in, tilt to "
                "top-down, staggered layer reveal, draw-on, fade out, 2D zoom. Each lands "
                "as ordinary keyframes you can then drag and re-ease.",
            ),
            Entry(
                "Play / pause",
                "Transport bar (Space)",
                "Wall-clock timed, so an animation "
                "authored at 5 seconds lasts 5 seconds at any frame rate.",
            ),
            Entry("Scrub", "Drag the playhead", "Shows the time and the frame number."),
            Entry("Step one frame", "Step buttons", "The exact frame an export will write."),
            Entry("Loop mode", "Loop button", "Once, loop, or ping-pong."),
            Entry(
                "Re-key one track",
                "Add keyframe",
                "Records the selected track's live value. Creates nothing — Capture is for "
                "that.",
            ),
            Entry(
                "Change the easing",
                "Keyframe inspector",
                "Linear, smooth, ease in/out, " "back, elastic, bounce — and Step.",
            ),
        ),
    ),
    Section(
        title="Interpolated or discrete — the choice that matters",
        intro=(
            "Two kinds of animation live on the same timeline and they are not the same "
            "thing.\n\n"
            "An **interpolated** track computes the values between its keyframes: a camera "
            "sweeping, a colour fading, a point moving. That is what easing is for.\n\n"
            "A **discrete progression** has no 'between'. Frame 12 of a Game of Life run, "
            "iteration 300 of a Mandelbrot zoom, step 40 of an integration — asking for the "
            "value at t = 3.5 must give you the state at step 3, not a blend of 3 and 4. "
            "Choose the 'Step (discrete)' easing for that, or switch the whole track's "
            "Interpolate off.\n\n"
            "This is enforced, not advisory: a track carrying values that cannot be blended "
            "— a grid, a label, a visibility flag — holds rather than mixing them. Half of "
            "one generation and half of the next is not a board."
        ),
    ),
    Section(
        title="Scenes and presenting",
        intro=(
            "A scene is a named span of the timeline — a chapter. Scenes are what turn an "
            "animation into a talk: instead of scrubbing blindly you get a list you can "
            "jump between, play one at a time, and advance with a clicker.\n\n"
            "A track may cross a scene boundary, because a scene is a view onto the "
            "timeline and not a container for it — which is what lets a camera move "
            "continue across a chapter change. 'Hold at end' stops at the scene's end so "
            "you control the pace."
        ),
    ),
    Section(
        title="Animating a process — Newton, Life, fractals",
        intro=(
            "Some animations are not keyframed at all: they are a simulation stepped "
            "forward. Thirteen are built in, across four groups.\n\n"
            "Mechanics: N-body gravity, two-body orbits, a projectile with drag, a driven "
            "damped pendulum, the double pendulum, a spring chain. These integrate "
            "Newton's equations — with a symplectic integrator where the force allows one, "
            "so the energy stays bounded instead of spiralling.\n\n"
            "Automata: Conway's Game of Life (block, blinker, toad, glider, LWSS, "
            "R-pentomino, acorn, Gosper gun, or random) and the elementary rules.\n\n"
            "Grids: Gray-Scott reaction-diffusion, and a 2D wave equation.\n\n"
            "Fractals: a Mandelbrot zoom, a Julia set with a moving parameter, and the "
            "chaos game (fern, Sierpinski, dragon, Lévy).\n\n"
            "A continuous process takes a real timestep and subdivides it internally, so "
            "accuracy does not depend on your frame rate. A discrete one has no timestep "
            "at all — one step is one generation, and asking for half a step is refused "
            "rather than faked."
        ),
    ),
    Section(
        title="Exporting an animation",
        intro=(
            "PNG frame sequence, animated GIF, or MP4. The frame sequence always works and "
            "needs nothing installed; GIF needs Pillow (matplotlib already depends on it); "
            "MP4 needs imageio-ffmpeg or an ffmpeg binary on PATH. A missing encoder says "
            "what to install rather than failing obscurely.\n\n"
            "Export walks the frame grid, never the playhead: playback may skip frames "
            "when the machine is busy, an export never does."
        ),
    ),
    Section(
        title="Math Lab — operate on a layer",
        intro=(
            "Integral, derivative, smoothing (Savitzky-Golay and Gaussian), noise, "
            "normalise, FFT, polynomial fit and statistics, applied to the selected layer. "
            "The preview draws the result against the original before you commit; Apply is "
            "a single undoable step."
        ),
    ),
    Section(
        title="Scene — the layer list",
        intro=(
            "Select, rename, hide, solo, duplicate, delete and reorder layers. Dragging a "
            "row changes list order only; explicit stacking is the zorder field in Style, "
            "which wins over list order."
        ),
    ),
    Section(
        title="Style — the selected layer's look",
        intro=(
            "Color, line width, point size, alpha, draw order, plus the view-wide settings: "
            "grid, labels, frame, density, glow, background. Fields that do nothing for the "
            "selected layer type are hidden rather than shown dead — a scatter has no line "
            "width, and a 3D layer ignores the 2D multipliers."
        ),
    ),
)


_TIPS: Tuple[Section, ...] = (
    Section(
        title="Paste straight from Excel",
        intro=(
            "Select cells in a spreadsheet, copy, and paste into the Data grid. The "
            "clipboard carries tab-separated text, which is exactly what the grid reads — "
            "no import step, no file. Paste as New Dataset makes a fresh sheet instead of "
            "overwriting the selection."
        ),
    ),
    Section(
        title="An edit moves the plot",
        intro=(
            "A dataset plotted from the Data panel keeps a link to its layer. Change a "
            "number and the curve follows on the next frame. Delete the layer and the table "
            "survives, merely unbound — your typing is never thrown away."
        ),
    ),
    Section(
        title="Unknown names become sliders",
        intro=(
            "In Functions, a * sin(b * x) gives you an a slider and a b slider without "
            "declaring anything. It is the fastest way to explore a family of curves: drag "
            "instead of retyping. Ranges are editable if the defaults are too tight."
        ),
    ),
    Section(
        title="Preview before you apply",
        intro=(
            "Every Math Lab operation draws its result over the original first. Tune the "
            "window, the order, the cutoff, and only then Apply. Nothing enters the scene "
            "while you are still deciding."
        ),
    ),
    Section(
        title="Drag to reorder layers",
        intro=(
            "The Scene list reorders by drag. If two layers still stack wrongly, they have "
            "an explicit zorder — set it in Style; it is sorted before list order."
        ),
    ),
    Section(
        title="min is not minimum",
        intro=(
            "min(y) and max(y) are reductions: they collapse an array to one number. "
            "minimum(y, 0) and maximum(y, 0) are elementwise: they return an array the same "
            "length as y. Clamping a curve at zero wants maximum, not max."
        ),
    ),
    Section(
        title="A 3D limit clips, a 2D limit does not",
        intro=(
            "set_zlim on a 3D figure discards geometry outside the range as well as "
            "moving the box, so it is a genuine view into a slab of the data. The 2D "
            "limits only move the camera. Clear them again with autoscale3d()."
        ),
    ),
    Section(
        title="Cube aspect changes the picture, not the numbers",
        intro=(
            "By default a 3D plot draws raw data units, so an axis spanning a million "
            "dwarfs one spanning one. 'Axis scaling: Cube' in the View 3D panel rescales "
            "each axis to the same on-screen length. The tick numbers stay true — only "
            "the shape changes."
        ),
    ),
    Section(
        title="matplotlib animation scripts run unchanged",
        intro=(
            "Swap the import and a matplotlib animation script works:\n\n"
            "    import glplot.animation as animation\n"
            "    ani = animation.FuncAnimation(fig, update, frames=200, interval=20)\n"
            "    ani.save('out.mp4', fps=30)\n\n"
            "FuncAnimation, ArtistAnimation and the writer registry all match matplotlib's "
            "signatures. 'blit' is accepted and ignored — the whole scene is re-rendered "
            "each frame — which is documented rather than silent."
        ),
    ),
    Section(
        title="Undo covers the whole workstation",
        intro=(
            "Cell edits, structural changes, plots, deletions and Math Lab applications all "
            "land on one undo stack. The Edit menu names the step you are about to undo."
        ),
    ),
)


# --------------------------------------------------------------------------------------
# The expression reference's prose. Keyed by name; the rows themselves are generated by
# walking SAFE_NAMES, so this table is documentation, not the list.
# --------------------------------------------------------------------------------------

_GROUP_ORDER: Tuple[str, ...] = (
    "Trigonometry",
    "Exponential & logarithmic",
    "Rounding & sign",
    "Statistics & reductions",
    "Construction",
    "Selection (elementwise)",
    "Constants",
    "Signal",
    "Convenience",
    "Other",
)

#: ``name -> (group, signature, one-line description)``.
_EXPR_DOCS: Dict[str, Tuple[str, str, str]] = {
    # -- trigonometry ------------------------------------------------------------------
    "sin": ("Trigonometry", "sin(x)", "Sine of x, in radians."),
    "cos": ("Trigonometry", "cos(x)", "Cosine of x, in radians."),
    "tan": ("Trigonometry", "tan(x)", "Tangent of x; blows up near ±pi/2."),
    "arcsin": ("Trigonometry", "arcsin(x)", "Inverse sine, radians; nan outside [-1, 1]."),
    "arccos": ("Trigonometry", "arccos(x)", "Inverse cosine, radians; nan outside [-1, 1]."),
    "arctan": ("Trigonometry", "arctan(x)", "Inverse tangent, radians in (-pi/2, pi/2)."),
    "arctan2": (
        "Trigonometry",
        "arctan2(y, x)",
        "Angle of the point (x, y) in (-pi, pi]; quadrant-correct.",
    ),
    "sinh": ("Trigonometry", "sinh(x)", "Hyperbolic sine."),
    "cosh": ("Trigonometry", "cosh(x)", "Hyperbolic cosine."),
    "tanh": ("Trigonometry", "tanh(x)", "Hyperbolic tangent; saturates at ±1."),
    "arcsinh": ("Trigonometry", "arcsinh(x)", "Inverse hyperbolic sine."),
    "arccosh": ("Trigonometry", "arccosh(x)", "Inverse hyperbolic cosine; needs x >= 1."),
    "arctanh": ("Trigonometry", "arctanh(x)", "Inverse hyperbolic tangent; needs |x| < 1."),
    # -- exponential / logarithmic -----------------------------------------------------
    "exp": ("Exponential & logarithmic", "exp(x)", "e raised to x."),
    "expm1": ("Exponential & logarithmic", "expm1(x)", "exp(x) - 1, accurate for tiny x."),
    "log": ("Exponential & logarithmic", "log(x)", "Natural log; -inf at 0, nan below."),
    "log2": ("Exponential & logarithmic", "log2(x)", "Base-2 logarithm."),
    "log10": ("Exponential & logarithmic", "log10(x)", "Base-10 logarithm."),
    "log1p": ("Exponential & logarithmic", "log1p(x)", "log(1 + x), accurate for tiny x."),
    "sqrt": ("Exponential & logarithmic", "sqrt(x)", "Square root; nan for negative x."),
    "cbrt": ("Exponential & logarithmic", "cbrt(x)", "Cube root; defined for negative x."),
    "power": ("Exponential & logarithmic", "power(x, y)", "x to the power y, elementwise."),
    # -- rounding / sign ---------------------------------------------------------------
    "abs": ("Rounding & sign", "abs(x)", "Absolute value."),
    "fabs": ("Rounding & sign", "fabs(x)", "Absolute value, always as a float."),
    "sign": ("Rounding & sign", "sign(x)", "-1 below zero, 0 at zero, +1 above."),
    "floor": ("Rounding & sign", "floor(x)", "Round down to an integer value."),
    "ceil": ("Rounding & sign", "ceil(x)", "Round up to an integer value."),
    "round": ("Rounding & sign", "round(x, decimals=0)", "Round to nearest; ties go to even."),
    "trunc": ("Rounding & sign", "trunc(x)", "Round toward zero."),
    "clip": ("Rounding & sign", "clip(x, lo, hi)", "Limit every sample to [lo, hi]."),
    "mod": ("Rounding & sign", "mod(x, y)", "Remainder, taking the sign of y."),
    # -- statistics / reductions -------------------------------------------------------
    "sum": ("Statistics & reductions", "sum(y)", "Total of every sample. One number."),
    "cumsum": ("Statistics & reductions", "cumsum(y)", "Running total; an array, not a number."),
    "prod": ("Statistics & reductions", "prod(y)", "Product of every sample."),
    "cumprod": ("Statistics & reductions", "cumprod(y)", "Running product."),
    "mean": ("Statistics & reductions", "mean(y)", "Arithmetic mean."),
    "median": ("Statistics & reductions", "median(y)", "Middle value."),
    "std": ("Statistics & reductions", "std(y)", "Standard deviation."),
    "var": ("Statistics & reductions", "var(y)", "Variance."),
    "min": ("Statistics & reductions", "min(y)", "Smallest sample. A reduction — see minimum."),
    "max": ("Statistics & reductions", "max(y)", "Largest sample. A reduction — see maximum."),
    "argmin": ("Statistics & reductions", "argmin(y)", "Index of the smallest sample."),
    "argmax": ("Statistics & reductions", "argmax(y)", "Index of the largest sample."),
    "ptp": ("Statistics & reductions", "ptp(y)", "Peak to peak: max(y) - min(y)."),
    # -- construction ------------------------------------------------------------------
    "linspace": (
        "Construction",
        "linspace(start, stop, num=50)",
        "Evenly spaced samples, both endpoints included.",
    ),
    "arange": (
        "Construction",
        "arange(start, stop, step=1)",
        "Like range(), as an array; stop is excluded.",
    ),
    "zeros": ("Construction", "zeros(n)", "n samples of 0."),
    "ones": ("Construction", "ones(n)", "n samples of 1."),
    "full": ("Construction", "full(n, value)", "n samples of value."),
    "array": ("Construction", "array([1, 2, 3])", "An array from a list literal."),
    # -- selection ---------------------------------------------------------------------
    "where": (
        "Selection (elementwise)",
        "where(cond, a, b)",
        "a where cond is true, b elsewhere. Try where(x > 0, x, 0).",
    ),
    "maximum": (
        "Selection (elementwise)",
        "maximum(a, b)",
        "Larger of the two, sample by sample. Not the max reduction.",
    ),
    "minimum": (
        "Selection (elementwise)",
        "minimum(a, b)",
        "Smaller of the two, sample by sample. Not the min reduction.",
    ),
    # -- constants ---------------------------------------------------------------------
    "pi": ("Constants", "pi", "3.14159265…"),
    "e": ("Constants", "e", "2.71828182… Shadowed if you name a parameter e."),
    "tau": ("Constants", "tau", "2*pi — one full turn."),
    "inf": ("Constants", "inf", "Positive infinity."),
    "nan": ("Constants", "nan", "Not a number. Breaks a line rather than drawing through."),
    # -- signal ------------------------------------------------------------------------
    "heaviside": (
        "Signal",
        "heaviside(x, x2=0.5)",
        "0 below zero, 1 above, x2 exactly at zero.",
    ),
    "sinc": ("Signal", "sinc(x)", "sin(pi*x)/(pi*x), and exactly 1 at x = 0."),
    "gradient": (
        "Signal",
        "gradient(y)",
        "Numerical derivative by central differences; same length as y.",
    ),
    "diff": ("Signal", "diff(y)", "Successive differences; one sample shorter than y."),
    "interp": ("Signal", "interp(x, xp, fp)", "Linearly interpolate the points (xp, fp) at x."),
    # -- convenience -------------------------------------------------------------------
    "gauss": (
        "Convenience",
        "gauss(x, mu=0, sigma=1)",
        "Gaussian bell peaking at exactly 1 — the curve, not the density.",
    ),
    "sigmoid": ("Convenience", "sigmoid(x)", "Logistic 1/(1+exp(-x)); never overflows."),
    "rect": ("Convenience", "rect(x)", "Rectangular pulse: 1 for |x| < 0.5, 0.5 at the edge."),
    "step": ("Convenience", "step(x)", "Unit step: 0 below zero, 1 from zero up."),
    "sawtooth": (
        "Convenience",
        "sawtooth(x, period=1)",
        "Rising ramp in [-1, 1), repeating every period.",
    ),
    "square": (
        "Convenience",
        "square(x, period=1)",
        "Square wave in {-1, 1}, high for the first half of each period.",
    ),
    "noise": (
        "Convenience",
        "noise(n_or_x, scale=1, seed=None)",
        "Gaussian noise shaped like an array, or n samples of it.",
    ),
}

_EXPR_INTRO = (
    "Everything an expression may name. Anything else you type is a free variable and "
    "becomes a parameter slider in Functions — that is a feature, not an error, which is "
    "why a typo like sni(x) is reported but a bare k is not. Attribute access, lambdas, "
    "comprehensions and imports are rejected at parse time."
)

_EXPR_REDUCTION_NOTE = (
    "min / max / mean / sum and friends are reductions: they collapse a whole array into "
    "one number, so min(y) plotted against x is a flat line. minimum / maximum are "
    "elementwise: minimum(y, 1) clamps every sample at 1 and returns an array. When you "
    "mean 'clamp', reach for minimum and maximum."
)


def _fallback_doc(name: str, value: Any) -> Tuple[str, str, str]:
    """Prose for a SAFE_NAMES entry that :data:`_EXPR_DOCS` does not cover.

    Keeps the reference honest when the evaluator gains a name and this table has not
    caught up: introspect the signature, take the docstring's first line, and file it under
    "Other" so the omission is visible rather than the function being invisible.
    """
    if not callable(value):
        return ("Other", name, "Constant.")
    signature = "{0}(…)".format(name)
    try:
        signature = "{0}{1}".format(name, inspect.signature(value))
    except (TypeError, ValueError):
        # numpy ufuncs are C objects with no introspectable signature. Expected.
        pass
    doc = (inspect.getdoc(value) or "").strip().splitlines()
    description = doc[0].strip() if doc else "No description available."
    return ("Other", signature, description)


def _expression_sections() -> Tuple[Section, ...]:
    """Build the Expressions reference by walking :data:`expressions.SAFE_NAMES`.

    The dict drives the rows; :data:`_EXPR_DOCS` only supplies prose. A name in the doc
    table that is no longer in ``SAFE_NAMES`` therefore disappears on its own, and a name
    added to ``SAFE_NAMES`` shows up whether or not anyone documented it.
    """
    grouped: Dict[str, List[Entry]] = {}
    for name, value in expressions.SAFE_NAMES.items():
        group, signature, description = _EXPR_DOCS.get(name) or _fallback_doc(name, value)
        # The signature doubles as the insert snippet: dropping "clip(x, lo, hi)" into the
        # editor leaves the argument names as placeholders to type over, which is more use
        # than a bare "clip(" that does not even parse.
        snippet = signature if callable(value) else name
        grouped.setdefault(group, []).append(
            Entry(label=signature, value=name, note=description, insert=snippet)
        )

    sections: List[Section] = []
    for group in _GROUP_ORDER:
        entries = grouped.pop(group, [])
        if entries:
            sections.append(
                Section(title=group, entries=tuple(entries), insertable=True, value_width=0.0)
            )
    # Any group invented by a future _EXPR_DOCS edit, so a typo'd group name cannot hide
    # rows off the end of _GROUP_ORDER.
    for group in sorted(grouped):
        sections.append(
            Section(title=group, entries=tuple(grouped[group]), insertable=True, value_width=0.0)
        )
    return tuple(sections)


# ======================================================================================
# The panel
# ======================================================================================


@dataclass(frozen=True)
class _Tab:
    """A tab: its stable id (used by :meth:`HelpPanel.show`) and its label."""

    id: str
    title: str


_TABS: Tuple[_Tab, ...] = (
    _Tab("start", "Getting Started"),
    _Tab("keyboard", "Keyboard"),
    _Tab("expressions", "Expressions"),
    _Tab("panels", "Panels"),
    _Tab("tips", "Tips"),
)


class HelpPanel(Panel):
    """Teach the workstation: a tour, the live keymap, the expression reference, tips."""

    title = "Help"
    icon = "info"
    default_open = False

    def __init__(self, ws: Any) -> None:
        super().__init__(ws)
        self._query: str = ""
        self._active_tab: str = _TABS[0].id
        #: Set by :meth:`show`; consumed by the next frame's tab/section rendering.
        self._pending_tab: Optional[str] = None
        self._pending_section: Optional[str] = None
        self._status: str = ""
        # SAFE_NAMES is a module-level dict that never changes at runtime, so the ~70-row
        # reference is built once rather than per frame.
        self._expr_sections: Tuple[Section, ...] = ()

    # -- public API (the palette's "?" provider talks to this) --------------------------

    def topics(self) -> List[Tuple[str, str]]:
        """Every addressable Help topic as ``(topic_id, title)``.

        Topic ids are ``"<tab>"`` or ``"<tab>/<section title>"``; both are accepted by
        :meth:`show`. The palette's ``?`` provider lists these.
        """
        out: List[Tuple[str, str]] = []
        for tab in _TABS:
            out.append((tab.id, tab.title))
            for section in self._sections_for(tab.id):
                topic_id = "{0}/{1}".format(tab.id, section.title)
                out.append((topic_id, "{0} · {1}".format(tab.title, section.title)))
        return out

    def show(self, topic_id: Optional[str] = None, *, query: str = "") -> None:
        """Open Help at ``topic_id`` (from :meth:`topics`), optionally with a search query.

        Safe to call from a draw callback: it only sets state that the next frame reads.
        An unknown topic falls back to selecting the first tab rather than raising — a
        stale palette entry must not take the frame down.
        """
        self.ws.open["help"] = True
        self._query = query
        self._status = ""
        if not topic_id:
            return
        tab_id, _, section_title = topic_id.partition("/")
        self._pending_tab = tab_id if any(t.id == tab_id for t in _TABS) else _TABS[0].id
        self._pending_section = section_title or None

    #: The name the command palette's ``?`` provider probes for
    #: (``open_topic`` / ``show_topic`` / ``select_topic``, in that order). Aliased rather
    #: than renamed: ``show`` is what the workspace's Help actions call, and one method with
    #: two names cannot drift from itself the way two implementations would.
    open_topic = show

    # -- content assembly --------------------------------------------------------------

    def _sections_for(self, tab_id: str) -> Tuple[Section, ...]:
        """The sections of a tab. Generated ones are rebuilt per call; static ones are not."""
        if tab_id == "keyboard":
            return self._keyboard_sections()
        if tab_id == "expressions":
            if not self._expr_sections:
                self._expr_sections = _expression_sections()
            return self._expr_sections
        if tab_id == "panels":
            return _PANEL_SECTIONS
        if tab_id == "tips":
            return _TIPS
        return ()

    def _keyboard_sections(self) -> Tuple[Section, ...]:
        """Generate the shortcut sheet from the workspace's ActionRegistry.

        Only actions that actually carry a chord are listed: this is a keyboard sheet, and
        the palette is where the unbound ones live. Rebuilt every frame, which is what
        keeps it truthful — an action registered late, or a predicate that just disabled
        one, shows up immediately.
        """
        registry = getattr(self.ws, "registry", None)
        if registry is None:
            return (
                Section(
                    title="Keyboard",
                    intro=(
                        "No action registry is attached to this workspace, so there are no "
                        "registered shortcuts to list. The engine hotkeys below still work."
                    ),
                ),
                Section(
                    title="Engine hotkeys",
                    intro=_ENGINE_INTRO,
                    entries=_ENGINE_HOTKEYS,
                    value_header="Key",
                ),
            )

        sections: List[Section] = []
        try:
            actions = registry.all()
            categories = registry.categories()
        except Exception:  # pragma: no cover - defensive: a foreign registry object
            logger.exception("Could not read the action registry.")
            return (Section(title="Keyboard", intro="The action registry could not be read."),)

        for category in categories:
            entries = tuple(
                Entry(
                    label=action.title,
                    value=keys.format(action.chord),
                    note=action.description,
                )
                for action in actions
                if action.category == category and action.chord is not None
            )
            if entries:
                sections.append(Section(title=category, entries=entries, value_header="Shortcut"))

        try:
            conflicts = registry.conflicts()
        except Exception:  # pragma: no cover - defensive
            conflicts = []
        if conflicts:
            sections.append(
                Section(
                    title="Conflicts ({0})".format(len(conflicts)),
                    intro=(
                        "These chords are bound to more than one enabled action. Only the "
                        "first one listed ever runs; the others are dead until one of them "
                        "is rebound."
                    ),
                    entries=tuple(
                        Entry(
                            label=", ".join(a.title for a in group),
                            value=keys.format(chord),
                            note="Only '{0}' runs.".format(group[0].title),
                        )
                        for chord, group in conflicts
                    ),
                    value_header="Shortcut",
                )
            )

        sections.append(
            Section(
                title="Engine hotkeys",
                intro=_ENGINE_INTRO,
                entries=_ENGINE_HOTKEYS,
                value_header="Key",
            )
        )
        return tuple(sections)

    # -- actions the buttons perform ---------------------------------------------------

    def _open_panel(self, key: str) -> bool:
        """Open and focus panel ``key``. False (with a status line) when it does not exist."""
        panel = self.ws.panels.get(key)
        if panel is None:
            self._status = "The {0} panel is not available.".format(key)
            return False
        self.ws.open_panel(key)
        return True

    def _run_step(self, step: Step) -> None:
        """Perform a Getting Started step: its registered action, else open its panel.

        The action is preferred so the button and the shortcut cannot diverge. Its ``run``
        already routes any scene mutation through ``ws.queue`` (CONTRACT §1.1), which is
        why calling it from this draw callback is legitimate.
        """
        registry = getattr(self.ws, "registry", None)
        if step.action_id and registry is not None:
            try:
                action = registry.get(step.action_id)
                if action is not None and registry.enabled(action):
                    action.run()
                    self._status = "Ran: {0}".format(action.title)
                    return
            except Exception:
                logger.exception("Help step %r failed to run action %r", step.title, step.action_id)
        if step.panel and self._open_panel(step.panel):
            self._status = "Opened the {0} panel.".format(self.ws.panels[step.panel].title)

    def _insert_expression(self, snippet: str) -> None:
        """Drop ``snippet`` into the Functions panel's expression, then focus that panel.

        Appended, not inserted at a caret: imgui's ``input_text`` does not expose one. A
        separator is added when the existing text would otherwise be glued into nonsense
        (``a * sin(x)`` + ``exp(x)`` -> ``a * sin(x) + exp(x)``), so the result always
        parses and the user edits from something valid.
        """
        panel = self.ws.panels.get("functions")
        if panel is None:
            self._status = "The Functions panel is not available."
            return
        current = str(getattr(panel, "expr", "") or "").rstrip()
        if not current:
            new = snippet
        elif current[-1] in "+-*/(,%":
            new = "{0} {1}".format(current, snippet)
        else:
            new = "{0} + {1}".format(current, snippet)
        panel.expr = new
        self.ws.open_panel("functions")
        self._status = "Inserted {0} into Functions.".format(snippet)

    # -- search ------------------------------------------------------------------------

    @staticmethod
    def _matches(query: str, labels: Tuple[str, ...], prose: Tuple[str, ...] = ()) -> bool:
        """True when ``query`` hits any label (fuzzily) or any prose field (as a substring).

        The two rules are deliberately different. Fuzzy subsequence matching is right for a
        short identifier -- "mnm" should find ``minimum`` -- but over a paragraph it matches
        almost everything, because the letters of any short query appear scattered through
        any long English sentence: searching "paste" that way returned six of the seven
        tips, and "trig" pulled in "Round to nearest; ties go to even". Prose therefore
        requires real containment. Empty query matches everything.
        """
        if not query:
            return True
        for text in labels:
            if text and fuzzy.score(query, text) is not None:
                return True
        lowered = query.lower()
        for text in prose:
            if text and lowered in text.lower():
                return True
        return False

    def _filter(self, sections: Tuple[Section, ...]) -> List[Section]:
        """Drop entries and whole sections that the query does not reach.

        A section whose *title or intro* matches keeps all its entries: the user searched
        for the topic, not for a row inside it, and handing them an empty section would be
        a worse answer than the section itself.
        """
        query = self._query.strip()
        if not query:
            return list(sections)
        out: List[Section] = []
        for section in sections:
            if self._matches(query, (section.title,), (section.intro,)):
                out.append(section)
                continue
            entries = tuple(
                e for e in section.entries if self._matches(query, e.labels(), e.prose())
            )
            if entries:
                out.append(
                    Section(
                        title=section.title,
                        intro=section.intro,
                        entries=entries,
                        value_header=section.value_header,
                        value_width=section.value_width,
                        insertable=section.insertable,
                    )
                )
        return out

    # -- drawing -----------------------------------------------------------------------

    def draw(self) -> None:
        """Render the panel body. The workspace owns the surrounding window."""
        if not IMGUI_AVAILABLE:
            return
        self._draw_header()
        self._draw_tabs()

    def _draw_header(self) -> None:
        """The one-line pitch, the shortcut hints, and the cross-tab search box."""
        imgui.text_disabled(
            "F1 opens this panel · {0} opens the command palette".format(_chord_text("Mod+K"))
        )
        imgui.spacing()

        imgui.push_item_width(-88.0)
        changed, value = imgui.input_text("##help_search", self._query)
        imgui.pop_item_width()
        if changed:
            self._query = value
        imgui.same_line()
        if imgui.button("Clear", (74.0, 0.0)):
            self._query = ""
        # pyimgui 2.0's input_text has no placeholder/hint parameter, so the prompt lives
        # under the field rather than inside it.
        imgui.text_disabled("Search every tab: a function, a shortcut, a panel.")
        if self._status:
            imgui.text_disabled(self._status)
        imgui.separator()

    def _draw_tabs(self) -> None:
        """The tab bar; each tab scrolls its own child region."""
        tab_bar_open = imgui.begin_tab_bar("##help_tabs")
        if not tab_bar_open:
            return
        for tab in _TABS:
            flags = 0
            if self._pending_tab == tab.id:
                flags = imgui.TabItemFlags_.set_selected
            selected, _ = imgui.begin_tab_item(tab.title, flags=flags)
            if selected:
                if self._pending_tab == tab.id:
                    self._pending_tab = None
                self._active_tab = tab.id
                imgui.begin_child("##help_body_{0}".format(tab.id), (0.0, 0.0))
                try:
                    self._draw_tab_body(tab.id)
                finally:
                    # end_child is unconditional (CONTRACT §2.2); the try/finally makes that
                    # true even if a section raises mid-body.
                    imgui.end_child()
                imgui.end_tab_item()
        imgui.end_tab_bar()

    def _draw_tab_body(self, tab_id: str) -> None:
        """Dispatch a tab to its renderer. Everything but the tour is sections."""
        if tab_id == "start":
            self._draw_steps()
            return
        sections = self._filter(self._sections_for(tab_id))
        if tab_id == "expressions":
            imgui.push_text_wrap_pos(0.0)
            imgui.text_wrapped(_EXPR_INTRO)
            imgui.spacing()
            imgui.text_disabled(_EXPR_REDUCTION_NOTE)
            imgui.pop_text_wrap_pos()
            imgui.spacing()
        if not sections:
            imgui.text_disabled('Nothing here matches "{0}".'.format(self._query.strip()))
            return
        for section in sections:
            self._draw_section(section)

    def _draw_steps(self) -> None:
        """The Getting Started tour: numbered steps, each with a button that does it."""
        query = self._query.strip()
        steps = [s for s in _STEPS if self._matches(query, (s.title, s.button), (s.body,))]
        imgui.push_text_wrap_pos(0.0)
        imgui.text_wrapped(
            "Five steps from an empty window to a styled plot. Every button below really "
            "does the thing it describes — press it and watch where the panel opens."
        )
        imgui.pop_text_wrap_pos()
        imgui.spacing()
        if not steps:
            imgui.text_disabled('No step matches "{0}".'.format(query))
            return
        for index, step in enumerate(_STEPS):
            if step not in steps:
                continue
            imgui.push_id("help_step_{0}".format(index))
            imgui.text("{0}. {1}".format(index + 1, step.title))
            imgui.indent(14.0)
            imgui.push_text_wrap_pos(0.0)
            imgui.text_disabled(step.body)
            imgui.pop_text_wrap_pos()
            imgui.spacing()
            if imgui.button(step.button):
                self._run_step(step)
            imgui.unindent(14.0)
            imgui.spacing()
            imgui.separator()
            imgui.spacing()
            imgui.pop_id()

    def _draw_section(self, section: Section) -> None:
        """One collapsing header: intro prose, then the entry table."""
        # While a query is active every surviving section opens: results hidden inside a
        # collapsed header read as "no results".
        if self._query.strip() or self._pending_section == section.title:
            imgui.set_next_item_open(True)
        # Default open, every section: a Help tab that greets the reader with a column of
        # collapsed headers has hidden the answer behind a click they have no reason to
        # make. imgui remembers whatever they collapse themselves.
        expanded = imgui.collapsing_header(section.title, flags=imgui.TreeNodeFlags_.default_open)
        if self._pending_section == section.title:
            imgui.set_scroll_here_y(0.15)
            self._pending_section = None
        if not expanded:
            return

        imgui.indent(8.0)
        if section.intro:
            imgui.push_text_wrap_pos(0.0)
            imgui.text_disabled(section.intro)
            imgui.pop_text_wrap_pos()
            imgui.spacing()
        if section.entries:
            self._draw_entries(section)
        imgui.unindent(8.0)
        imgui.spacing()

    def _draw_entries(self, section: Section) -> None:
        """The two- or three-column entry table.

        ``begin_table`` returns False when it is clipped or out of space (CONTRACT
        §2.3), so ``end_table`` is called only inside the guard.
        """
        columns = 3 if section.insertable else 2
        flags = imgui.TableFlags_.row_bg | imgui.TableFlags_.borders_inner_h
        table_open = imgui.begin_table("##entries_{0}".format(section.title), columns, flags=flags)
        if not table_open:
            return
        try:
            if section.insertable:
                imgui.table_setup_column(
                    "Name", imgui.TableColumnFlags_.width_fixed, _SIGNATURE_COLUMN_W
                )
                imgui.table_setup_column("What it does", imgui.TableColumnFlags_.width_stretch)
                imgui.table_setup_column("", imgui.TableColumnFlags_.width_fixed, 62.0)
            else:
                imgui.table_setup_column("Action", imgui.TableColumnFlags_.width_stretch)
                imgui.table_setup_column(
                    section.value_header or "Key",
                    imgui.TableColumnFlags_.width_fixed,
                    section.value_width or _KEY_COLUMN_W,
                )
                if section.value_header:
                    imgui.table_headers_row()

            for index, entry in enumerate(section.entries):
                imgui.table_next_row()
                if section.insertable:
                    self._draw_insertable_row(section, index, entry)
                else:
                    self._draw_entry_row(entry)
        finally:
            imgui.end_table()

    @staticmethod
    def _draw_entry_row(entry: Entry) -> None:
        """A label (+ dimmed note beneath it) and its key column."""
        imgui.table_next_column()
        imgui.text(entry.label)
        if entry.note:
            imgui.push_text_wrap_pos(0.0)
            imgui.text_disabled(entry.note)
            imgui.pop_text_wrap_pos()
        imgui.table_next_column()
        imgui.text(entry.value)

    def _draw_insertable_row(self, section: Section, index: int, entry: Entry) -> None:
        """An expression row: signature, description, and an Insert button that means it."""
        imgui.table_next_column()
        imgui.text(entry.label)
        imgui.table_next_column()
        imgui.push_text_wrap_pos(0.0)
        imgui.text_disabled(entry.note)
        imgui.pop_text_wrap_pos()
        imgui.table_next_column()
        if entry.insert:
            imgui.push_id("ins_{0}_{1}".format(section.title, index))
            if imgui.small_button("Insert"):
                self._insert_expression(entry.insert)
            if imgui.is_item_hovered():
                imgui.set_tooltip("Append {0} to the Functions expression".format(entry.insert))
            imgui.pop_id()


def _chord_text(spec: str) -> str:
    """Format a chord spec for display, degrading to the spec itself if it will not parse."""
    try:
        return keys.format(keys.parse(spec))
    except ValueError:  # pragma: no cover - the specs here are literals
        return spec
